---
title: 'Agradecimientos'
---

**Gracias** a la comunidad de NaturalistaUY y a la red global de iNaturalist, por sus contribuciones a generar una plataforma que mejora el acceso al conocimiento sobre la biodiversidad en Uruguay y el mundo. 

**Gracias** al resto del equipo que llevó adelante los eventos: Gabriel Perazza, Alejandro Duarte, Mariana Pírez, y a quienes participaron de las jornadas, en particular a quienes fueron interlocutores por los colectivos locales: Mauro Zunino e Indira Manzano integrantes de Ubajay y San José Más Verde (San José), Daniel Macías de GruPAmA (Bella Unión) y Alcira Cremona de Paysandú Nuestro y GENSA (Paysandú). 

**Gracias** también a la comunidad de personas usuarias que brindó su apoyo en la plataforma durante la realización de los eventos: Ary Mailhos, Andrés González, Gabriel Laufer, Diego Caballero y Lucía Rodríguez. 



--- 

Este proyecto fue apoyado por el fondo "*Citizen-science for Species Discovery*" de la **National Geographic Society** (NGS-69405C-20).

