---
title: 'Reflexiones'
lang: es
---

Cada colectivo con el que trabajamos se acercó con intereses diferentes, desde la promoción del ecoturismo y la restauración de la biodiversidad de su zona, hasta el registro de especies y la defensa de su territorio. Todos los colectivos resaltaron el componente educativo y comunitario de la herramienta y los encuentros.

Tanto a Biodiversidata como a JULANA nos preocupa e interesa promover el uso y apropiación de los datos generados, más allá de la recolección. Encontramos en estos encuentros la posibilidad de hacer confluir ambas cosas.

## ¿Qué implica hacer ciencia comunitaria desde una perspectiva crítica?

Desgeneralizar la práctica para permitir que en cada evento de registro de la biodiversidad también emerjan reflexiones y desafíos propios de las personas en sus comunidades. Enfocarse en contribuir al fortalecimiento de las comunidades en el marco de procesos que los colectivos están atravesando.  

Usar metodologías que promuevan la participación de todas las personas e inviten a reflexionar acerca del contexto socio-político en el que se llevan a cabo. Generar espacios de intercambio y debate, que habiliten diálogos sobre la participación social en la generación de conocimiento colectivo y el acceso de las personas a datos sobre la biodiversidad. 

## ¿Qué potencialidades tiene la herramienta?

El uso de NaturalistaUY puede adoptar una forma comunitaria y ser apropiado colectivamente, porque:

  - No es necesario contar con formación científica para tomar la información disponible y generar productos con respaldo científico (por ejemplo un listado de especies).  
  - No se realiza una diferenciación entre las personas usuarias que adoptan diferentes roles, por ejemplo en la observación o en la identificación de especies, generando una comunidad virtual con estructura horizontal.  
  - Facilita la integración de diferentes generaciones, permitiendo que personas jóvenes se involucren en estos temas al contribuir con su habilidad y entusiasmo por el uso de tecnologías.
  - Habilita una interacción entre colectivos en el marco de los eventos como por la comunidad virtual que se construye dentro de la plataforma.  
